import Head from "next/head";


import { api } from "~/utils/api";
import {useState} from "react";
import {Box, Button, ColorSchemeScript, Group, Input, ScrollArea, Text, Title} from "@mantine/core";
import {Chat, Message} from "~/Components/Chat";


export default function Home() {
  const [messages, setMessages] = useState<Message[]>([])
  const [prompt, setPrompt] = useState("")
  const mut = api.ai.getPromptOutput.useMutation();


  const addPrompt = async () => {
    const newMsg: Message = {
      text: prompt,
      sender: "user"
    };

    setMessages((prev) => [...prev, newMsg])
    setPrompt("")

    const res = await mut.mutateAsync({
      prompt: prompt
    });

    const newMsg2: Message = {
      text: res.text,
      sender: "ai"
    }

    setMessages((prev) => [...prev, newMsg2])
  }



  return (
    <>
      <Head>
        <title>WebDev - AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <ColorSchemeScript />
      </Head>
      <main>
        <Box style={{

          display: "flex",
          flexDirection: "column",
          justifyItems: "center",
          alignItems: "center",
          width: "100%",
          height: "100vh",
        }}>
          <Box style={{
            maxWidth: "800px",
            height: "100%",
            width: "100%",
          }}>
            <Title className={"text-white"}>Chat</Title>
            <Chat messages={messages} isLoading={mut.isLoading} />
            <Group w={"100%"} mt={"2rem"}>
              <Button color={"red"} onClick={()=> {
                setMessages([])
              }}>Clear</Button>
              <Input style={{
                flexGrow: 1
              }} value={prompt} onChange={(event)=> {
                setPrompt(event.target.value)
              }} onSubmit={()=> console.log("AAAAAA")}/>
              <Button type={"submit"} onClick={()=> {void addPrompt()}}>Send</Button>
            </Group>
          </Box>
        </Box>

      </main>
    </>
  );
}
